<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\identity.entity\identity.entity.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pages\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\SendMail\ForgotPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Views\SendMail\ResetPassword.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="SendMail\ForgotPassword.cshtml" />
      <AdditionalFiles Include="SendMail\ResetPassword.cshtml" />
    </ItemGroup>

</Project>